### ISSUE TITLE
Rate limited: message

### ISSUE THREAD

**Issue by pedrito1414** [rowheat02/osm-gpt#4]
Hi, my queries aren't working. I am getting a **Rate Limited:** message every time...

![image](https://github.com/rowheat02/osm-gpt/assets/8447248/09890fbb-379d-48c1-a0aa-9f58d9515c5f)

**Comment by rowheat02** [comment]
I was not expecting this much traffic to the site so I was using openai API in the "Free Trial" plan, with an API rate limit.
I have upgraded my open API to a "Pay as you go" plan, so now you should not get Rate limited errors frequently. 

Also, you can build your own osm-gpt, with your own openai apikey as instructed in the readme file.
@pedrito1414

**Comment by Visdoom** [comment]
I added my own API key but am also running into those rate limited errors. Any hints?
