### ISSUE TITLE
Combined Searches

### ISSUE THREAD

**Issue by MyNameIsTroll** [rowheat02/osm-gpt#7]
Thanks for this great tool.

I noticed that combined searches don't seem to work.

I tried: 
-Displays wheelchair accessible museums.
- Display fountains near the train station.

But each time I get an error.

**Comment by rowheat02** [comment]
Hi @MyNameIsTroll, I'm currently using GPT-3, but it has some limitations when it comes to accurately answering complex osm queries. To address this issue and avoid the cost of using GPT-3, we're researching an open-source alternative model and fine-tuning it.
see the progress here #1

**Comment by MyNameIsTroll** [comment]
@rowheat02 
I understand, wise decision :) 
Thank you for your reply.
